package adminweb

// Code-shaped data, generated once from the panel's actual t() call arguments (the live
// key set) by scratchpad/extract-livekeys.mjs, then committed. It is the source of record
// the seed command writes into panel_text: En is the English base every key is authored
// in (identical to the key, which is the English source string), Es preserves the panel's
// prior Spanish translation where one existed. The panel renders a single language
// (English) by injecting the en rows; the es rows are retained so no translation work is
// lost and a future translate pass has a base. Keys from removed panels (Runs/Editorial/
// Prompts/Health), option VALUES (active/inactive/off), and the server-rendered login
// strings are not t() arguments and are absent here.

// PanelTextSeedEntry is one seed row: the stable key, its English base value, and the
// preserved Spanish value ("" when the key never had a Spanish overlay).
type PanelTextSeedEntry struct {
	Key string
	En  string
	Es  string
}

// PanelTextSeed returns the live panel UI-string catalog: 236 keys.
func PanelTextSeed() []PanelTextSeedEntry {
	return panelTextSeed
}

var panelTextSeed = []PanelTextSeedEntry{
	{"(file default)", "(file default)", "(valor del archivo)"},
	{"(lane default)", "(lane default)", "(valor del carril)"},
	{"(unset)", "(unset)", "(sin definir)"},
	{"A monthly schedule needs at least one day of the month.", "A monthly schedule needs at least one day of the month.", "Un cronograma mensual necesita al menos un día del mes."},
	{"A portada is one day's front-page plan. Pick a day, then order its articles (the first row is the day's lead), and mark any as important. Saving writes just that day; the articles themselves are untouched.", "A portada is one day's front-page plan. Pick a day, then order its articles (the first row is the day's lead), and mark any as important. Saving writes just that day; the articles themselves are untouched.", "Una portada es el plan de tapa de un día. Elija un día, luego ordene sus artículos (la primera fila es la nota de tapa del día) y marque los que sean importantes. Guardar escribe solo ese día; los artículos en sí no se tocan."},
	{"A schedule fires the newsroom's edition batch on its days at each listed time (the server's local wall clock). Preview holds every article for approval; auto publishes as soon as the gate passes. The executor runs while Docker runs: times missed while it is off are skipped, never replayed.", "A schedule fires the newsroom's edition batch on its days at each listed time (the server's local wall clock). Preview holds every article for approval; auto publishes as soon as the gate passes. The executor runs while Docker runs: times missed while it is off are skipped, never replayed.", "Un cronograma dispara el lote de edición de la redacción en sus días, a cada hora listada (reloj local del servidor). Preview retiene cada artículo para aprobación; auto publica apenas pasa la mesa. El ejecutor corre mientras Docker corre: las horas perdidas con el sistema apagado se saltean, nunca se repiten."},
	{"A schedule needs a name.", "A schedule needs a name.", "Un cronograma necesita un nombre."},
	{"A weekly schedule needs at least one weekday.", "A weekly schedule needs at least one weekday.", "Un cronograma semanal necesita al menos un día de la semana."},
	{"About", "About", "Acerca de"},
	{"Acta (research read)", "Acta (research read)", "Acta (lectura de investigación)"},
	{"Action failed ({code}): {msg}", "Action failed ({code}): {msg}", "La acción falló ({code}): {msg}"},
	{"Active", "Active", "Activo"},
	{"Active on this author", "Active on this author", ""},
	{"Add", "Add", "Agregar"},
	{"Add at least one time.", "Add at least one time.", "Agregue al menos una hora."},
	{"Add sources in the Sources tab first.", "Add sources in the Sources tab first.", "Primero agregue fuentes en la pestaña Fuentes."},
	{"Add time", "Add time", "Agregar hora"},
	{"Admin Panel", "Admin Panel", "Panel de administración"},
	{"All", "All", "Todo"},
	{"All authors", "All authors", "Todos los autores"},
	{"All days", "All days", "Todos los días"},
	{"All sections", "All sections", "Todas las secciones"},
	{"Alphabetical", "Alphabetical", "Alfabético"},
	{"An author only researches the sources linked here. Cross-source corroboration across them is what drives relevance: a claim that several linked outlets carry independently rises, an unsourced one does not. Link a few trusted, independent outlets per author.", "An author only researches the sources linked here. Cross-source corroboration across them is what drives relevance: a claim that several linked outlets carry independently rises, an unsourced one does not. Link a few trusted, independent outlets per author.", "Un autor solo investiga las fuentes vinculadas aquí. La corroboración entre fuentes es lo que impulsa la relevancia: una afirmación que varios medios vinculados sostienen de forma independiente sube, una sin fuente no. Vincule unos pocos medios confiables e independientes por autor."},
	{"Article", "Article", "Artículo"},
	{"Article deleted.", "Article deleted.", "Artículo eliminado."},
	{"Article editor", "Article editor", "Editor de artículo"},
	{"Article saved.", "Article saved.", "Artículo guardado."},
	{"Articles", "Articles", "Artículos"},
	{"Ascending", "Ascending", "Ascendente"},
	{"Assigned to", "Assigned to", "Asignado a"},
	{"Author", "Author", "Autor"},
	{"Author editor", "Author editor", "Editor de autor"},
	{"Authors", "Authors", "Autores"},
	{"Auto", "Auto", "Auto"},
	{"Auto (publish on gate pass)", "Auto (publish on gate pass)", "Auto (publica al pasar la mesa)"},
	{"Automation", "Automation", "Automatización"},
	{"Avatar path", "Avatar path", "Ruta del avatar"},
	{"Avatar preview", "Avatar preview", "Vista previa del avatar"},
	{"Back", "Back", "Volver"},
	{"Beat", "Beat", "Sección"},
	{"Body", "Body", "Cuerpo"},
	{"Cadence", "Cadence", "Cadencia"},
	{"Cancel", "Cancel", "Cancelar"},
	{"Card size", "Card size", "Tamaño"},
	{"Card span", "Card span", "Extensión"},
	{"Clear filters", "Clear filters", "Limpiar filtros"},
	{"Close", "Close", "Cerrar"},
	{"Co-owned mastheads collapse to one independent source for the corroboration gate. Give shared owners the same group so two papers under one owner count once, not twice, when a claim needs a second source.", "Co-owned mastheads collapse to one independent source for the corroboration gate. Give shared owners the same group so two papers under one owner count once, not twice, when a claim needs a second source.", "Las cabeceras de un mismo dueño se cuentan como una sola fuente independiente para el control de corroboración. Asigne el mismo grupo a los dueños compartidos para que dos periódicos de un mismo dueño cuenten una vez, no dos, cuando una afirmación necesita una segunda fuente."},
	{"Complete all author fields before saving.", "Complete all author fields before saving.", "Complete todos los campos del autor antes de guardar."},
	{"Confirm", "Confirm", "Confirmar"},
	{"Console sections", "Console sections", "Secciones de la consola"},
	{"Control panel", "Control panel", "Panel de control"},
	{"Corrector", "Corrector", "Corrector"},
	{"Could not create author: {msg}", "Could not create author: {msg}", "No se pudo crear el autor: {msg}"},
	{"Could not delete article ({code}): {msg}", "Could not delete article ({code}): {msg}", "No se pudo eliminar el artículo ({code}): {msg}"},
	{"Could not load article: {msg}", "Could not load article: {msg}", "No se pudo cargar el artículo: {msg}"},
	{"Could not load articles: {msg}", "Could not load articles: {msg}", "No se pudo cargar los artículos: {msg}"},
	{"Could not load authors: {msg}", "Could not load authors: {msg}", "No se pudo cargar los autores: {msg}"},
	{"Could not load model settings: {msg}", "Could not load model settings: {msg}", "No se pudo cargar la configuración de modelos: {msg}"},
	{"Could not load portadas: {msg}", "Could not load portadas: {msg}", "No se pudo cargar las portadas: {msg}"},
	{"Could not load recomendado: {msg}", "Could not load recomendado: {msg}", "No se pudo cargar recomendado: {msg}"},
	{"Could not load schedules: {msg}", "Could not load schedules: {msg}", "No se pudieron cargar los cronogramas: {msg}"},
	{"Could not load sources: {msg}", "Could not load sources: {msg}", "No se pudo cargar las fuentes: {msg}"},
	{"Could not load topics: {msg}", "Could not load topics: {msg}", "No se pudo cargar los temas: {msg}"},
	{"Could not save ({code}): {msg}", "Could not save ({code}): {msg}", "No se pudo guardar ({code}): {msg}"},
	{"Could not save article ({code}): {msg}", "Could not save article ({code}): {msg}", "No se pudo guardar el artículo ({code}): {msg}"},
	{"Could not save portada ({code}): {msg}", "Could not save portada ({code}): {msg}", "No se pudo guardar la portada ({code}): {msg}"},
	{"Could not save recomendado ({code}): {msg}", "Could not save recomendado ({code}): {msg}", "No se pudo guardar recomendado ({code}): {msg}"},
	{"Create author", "Create author", "Crear autor"},
	{"Created {id}.", "Created {id}.", "Se creó {id}."},
	{"Creating...", "Creating...", "Creando..."},
	{"Daily", "Daily", "Diario"},
	{"Dark", "Dark", "Oscuro"},
	{"Date", "Date", "Fecha"},
	{"Date order", "Date order", "Orden de fecha"},
	{"Day", "Day", "Día"},
	{"Days", "Days", "Días"},
	{"Days of the month", "Days of the month", "Días del mes"},
	{"Delete", "Delete", "Eliminar"},
	{"Delete article", "Delete article", "Eliminar artículo"},
	{"Delete article?", "Delete article?", "¿Eliminar artículo?"},
	{"Deleting article...", "Deleting article...", "Eliminando artículo..."},
	{"Descending", "Descending", "Descendente"},
	{"Description", "Description", "Descripción"},
	{"Display name", "Display name", "Nombre visible"},
	{"Display name must contain letters or digits.", "Display name must contain letters or digits.", ""},
	{"Domain", "Domain", "Dominio"},
	{"Double card", "Double card", "Tarjeta doble"},
	{"Draft", "Draft", "Borrador"},
	{"Drag to reorder", "Drag to reorder", "Arrastrar para reordenar"},
	{"Edit article", "Edit article", "Editar artículo"},
	{"Enabled", "Enabled", "Habilitada"},
	{"Endpoint", "Endpoint", "Endpoint"},
	{"Feed URLs (comma separated)", "Feed URLs (comma separated)", "URLs de feeds (separadas por comas)"},
	{"Feed type", "Feed type", "Tipo de feed"},
	{"Female", "Female", ""},
	{"File default", "File default", "Valor del archivo"},
	{"Filter by active on this author", "Filter by active on this author", ""},
	{"Filter by author", "Filter by author", "Filtrar por autor"},
	{"Filter by day", "Filter by day", "Filtrar por día"},
	{"Filter by orientation", "Filter by orientation", "Filtrar por orientación"},
	{"Filter topics", "Filter topics", "Filtrar temas"},
	{"Full row", "Full row", "Fila completa"},
	{"Gate (editor de mesa)", "Gate (editor de mesa)", "Mesa (editor de mesa)"},
	{"Gender", "Gender", ""},
	{"Homepage", "Homepage", "Página principal"},
	{"Image", "Image", "Imagen"},
	{"Inactive", "Inactive", ""},
	{"Lane", "Lane", "Carril"},
	{"Language", "Language", "Idioma"},
	{"Last run", "Last run", "Última corrida"},
	{"Latest first", "Latest first", "Más recientes"},
	{"Leave every author unchecked to run the whole newsroom: each author with a beat and linked sources pitches candidates. Check authors to restrict the edition to them.", "Leave every author unchecked to run the whole newsroom: each author with a beat and linked sources pitches candidates. Check authors to restrict the edition to them.", "Deje todos los autores sin marcar para correr toda la redacción: cada autor con sección y fuentes vinculadas propone candidatas. Marque autores para restringir la edición a ellos."},
	{"Left", "Left", "Izquierda"},
	{"Light", "Light", "Claro"},
	{"Linked sources", "Linked sources", "Fuentes vinculadas"},
	{"Loading article...", "Loading article...", "Cargando artículo..."},
	{"Loading articles...", "Loading articles...", "Cargando artículos..."},
	{"Loading authors...", "Loading authors...", "Cargando autores..."},
	{"Loading recomendado...", "Loading recomendado...", "Cargando recomendado..."},
	{"Loading schedules...", "Loading schedules...", "Cargando cronogramas..."},
	{"Loading sources...", "Loading sources...", "Cargando fuentes..."},
	{"Loading topics...", "Loading topics...", "Cargando temas..."},
	{"Local (llama.cpp)", "Local (llama.cpp)", "Local (llama.cpp)"},
	{"Main article", "Main article", "Artículo principal"},
	{"Make {title} a full row", "Make {title} a full row", "Convertir {title} en fila completa"},
	{"Male", "Male", ""},
	{"Media", "Media", "Media"},
	{"Mode", "Mode", "Modo"},
	{"Model", "Model", "Modelo"},
	{"Model override", "Model override", "Modelo específico"},
	{"Models", "Models", "Modelos"},
	{"Models saved. The next firing uses them.", "Models saved. The next firing uses them.", "Modelos guardados. La próxima corrida los usa."},
	{"Monthly", "Monthly", "Mensual"},
	{"Most used", "Most used", "Más usados"},
	{"Move down", "Move down", "Bajar"},
	{"Move up", "Move up", "Subir"},
	{"Name", "Name", "Nombre"},
	{"Neutral", "Neutral", "Neutral"},
	{"New schedule", "New schedule", "Nuevo cronograma"},
	{"Next day", "Next day", "Día siguiente"},
	{"Next run", "Next run", "Próxima corrida"},
	{"No articles match.", "No articles match.", "Ningún artículo coincide."},
	{"No articles yet.", "No articles yet.", "Todavía no hay artículos."},
	{"No authors assigned", "No authors assigned", "Sin autores asignados"},
	{"No authors match.", "No authors match.", "Ningún autor coincide."},
	{"No authors registered yet.", "No authors registered yet.", "Todavía no hay autores registrados."},
	{"No authors yet.", "No authors yet.", "Todavía no hay autores."},
	{"No authors yet. Create one to get started.", "No authors yet. Create one to get started.", ""},
	{"No days", "No days", "Sin días"},
	{"No days match.", "No days match.", "Ningún día coincide."},
	{"No recommended articles selected.", "No recommended articles selected.", "No hay artículos recomendados seleccionados."},
	{"No runs recorded yet.", "No runs recorded yet.", "Todavía no hay corridas registradas."},
	{"No schedules yet. Create one to put the newsroom on a clock.", "No schedules yet. Create one to put the newsroom on a clock.", "Todavía no hay cronogramas. Cree uno para poner la redacción en horario."},
	{"No sources match.", "No sources match.", "Ninguna fuente coincide."},
	{"No sources yet.", "No sources yet.", "Todavía no hay fuentes."},
	{"No times yet.", "No times yet.", "Todavía no hay horas."},
	{"No topics yet.", "No topics yet.", "Todavía no hay temas."},
	{"Nonbinary", "Nonbinary", ""},
	{"On days of the month", "On days of the month", "En los días del mes"},
	{"On weekdays", "On weekdays", "En los días de la semana"},
	{"OpenRouter", "OpenRouter", "OpenRouter"},
	{"Order by", "Order by", "Ordenar por"},
	{"Orientation", "Orientation", "Orientación"},
	{"Outline", "Outline", "Esquema"},
	{"Ownership group", "Ownership group", "Grupo de propiedad"},
	{"Paused", "Paused", "Pausado"},
	{"Place after {title}", "Place after {title}", "Colocar después de {title}"},
	{"Place before {title}", "Place before {title}", "Colocar antes de {title}"},
	{"Portada", "Portada", "Portada"},
	{"Portada saved.", "Portada saved.", ""},
	{"Preview", "Preview", "Preview"},
	{"Preview (hold for approval)", "Preview (hold for approval)", "Preview (retiene para aprobación)"},
	{"Primary", "Primary", "Principal"},
	{"Prompt instructions", "Prompt instructions", "Instrucciones de prompt"},
	{"Recent runs", "Recent runs", "Corridas recientes"},
	{"Recomendado", "Recomendado", "Recomendado"},
	{"Recomendado saved.", "Recomendado saved.", "Recomendado guardado."},
	{"Remove {time}", "Remove {time}", "Quitar {time}"},
	{"Removed / unresolved", "Removed / unresolved", "Eliminado / sin resolver"},
	{"Research queries", "Research queries", "Consultas de investigación"},
	{"Restore", "Restore", "Restaurar"},
	{"Right", "Right", "Derecha"},
	{"Role for {title}", "Role for {title}", "Rol de {title}"},
	{"Save", "Save", "Guardar"},
	{"Save article", "Save article", "Guardar artículo"},
	{"Save models", "Save models", "Guardar modelos"},
	{"Save portada", "Save portada", ""},
	{"Saved.", "Saved.", "Guardado."},
	{"Saving...", "Saving...", "Guardando..."},
	{"Schedule", "Schedule", "Cronograma"},
	{"Schedule editor", "Schedule editor", "Editor de cronograma"},
	{"Schedules", "Schedules", "Cronogramas"},
	{"Search", "Search", "Buscar"},
	{"Search articles", "Search articles", "Buscar artículos"},
	{"Search authors", "Search authors", "Buscar autores"},
	{"Search days", "Search days", "Buscar días"},
	{"Search results", "Search results", "Resultados de búsqueda"},
	{"Search title and description", "Search title and description", "Buscar título y descripción"},
	{"Section", "Section", "Sección"},
	{"Sections", "Sections", "Secciones"},
	{"Select a beat", "Select a beat", "Elija una sección"},
	{"Show", "Show", "Mostrar"},
	{"Single card", "Single card", "Tarjeta simple"},
	{"Source", "Source", "Fuente"},
	{"Source editor", "Source editor", "Editor de fuente"},
	{"Sources", "Sources", "Fuentes"},
	{"Stage", "Stage", "Etapa"},
	{"Style", "Style", "Estilo"},
	{"Subtitle", "Subtitle", "Subtítulo"},
	{"System", "System", "Sistema"},
	{"Text", "Text", "Texto"},
	{"The time {time} is already on the list.", "The time {time} is already on the list.", "La hora {time} ya está en la lista."},
	{"Theme", "Theme", "Tema"},
	{"These settings steer the scheduled batches: each stage of the pipeline runs on the lane you pick, with an optional model override. A blank field keeps the pipeline file's default. The OpenRouter key is read from the stack's .env (OPENROUTER_API_KEY), never stored here.", "These settings steer the scheduled batches: each stage of the pipeline runs on the lane you pick, with an optional model override. A blank field keeps the pipeline file's default. The OpenRouter key is read from the stack's .env (OPENROUTER_API_KEY), never stored here.", "Esta configuración gobierna los lotes programados: cada etapa del pipeline corre en el carril elegido, con un modelo específico opcional. Un campo vacío conserva el valor del archivo del pipeline. La clave de OpenRouter se lee del .env del stack (OPENROUTER_API_KEY), nunca se guarda acá."},
	{"This article will be removed from this list. There is no recovery from this screen.", "This article will be removed from this list. There is no recovery from this screen.", "El artículo se quitará de esta lista. No hay recuperación desde esta pantalla."},
	{"Times", "Times", "Horas"},
	{"Times (several per day allowed)", "Times (several per day allowed)", "Horas (se permiten varias por día)"},
	{"Title", "Title", "Título"},
	{"Topics", "Topics", "Temas"},
	{"Topics are derived from the published article corpus, not a separate store. Filter or order them to inspect the tag surface.", "Topics are derived from the published article corpus, not a separate store. Filter or order them to inspect the tag surface.", "Los temas se derivan del corpus de artículos publicados, no de un registro separado. Filtre u ordene para revisar la superficie de etiquetas."},
	{"Unspecified", "Unspecified", ""},
	{"Up to {n} articles.", "Up to {n} articles.", "Hasta {n} artículos."},
	{"Weekdays", "Weekdays", "Días de la semana"},
	{"Weekly", "Weekly", "Semanal"},
	{"Who I am", "Who I am", "Quién soy"},
	{"YouTube", "YouTube", "YouTube"},
	{"failed", "failed", "falló"},
	{"never", "never", "nunca"},
	{"never ran", "never ran", "nunca corrió"},
	{"offline", "offline", "fuera de línea"},
	{"ok", "ok", "ok"},
	{"online", "online", "en línea"},
	{"running", "running", "corriendo"},
	{"unknown", "unknown", "desconocido"},
}
