package adminweb

// Code-shaped data, generated once from the panel's actual t() call arguments (the live
// key set) by scratchpad/extract-livekeys.mjs, then committed. It is the source of record
// the seed command writes into panel_text: En is the English base every key is authored
// in (identical to the key, which is the English source string), Es preserves the panel's
// prior Spanish translation where one existed. The panel renders a single language
// (English) by injecting the en rows; the es rows are retained so no translation work is
// lost and a future translate pass has a base. Keys from removed panels (Runs/Editorial/
// Prompts/Health), option VALUES (active/inactive/off), and the server-rendered login
// strings are not t() arguments and are absent here.

// PanelTextSeedEntry is one seed row: the stable key, its English base value, and the
// preserved Spanish value ("" when the key never had a Spanish overlay).
type PanelTextSeedEntry struct {
	Key string
	En  string
	Es  string
}

// PanelTextSeed returns the live panel UI-string catalog: 170 keys.
func PanelTextSeed() []PanelTextSeedEntry {
	return panelTextSeed
}

var panelTextSeed = []PanelTextSeedEntry{
	{"(unset)", "(unset)", "(sin definir)"},
	{"A portada is one day's front-page plan. Pick a day, then order its articles (the first row is the day's lead), and mark any as important. Saving writes just that day; the articles themselves are untouched.", "A portada is one day's front-page plan. Pick a day, then order its articles (the first row is the day's lead), and mark any as important. Saving writes just that day; the articles themselves are untouched.", "Una portada es el plan de tapa de un día. Elija un día, luego ordene sus artículos (la primera fila es la nota de tapa del día) y marque los que sean importantes. Guardar escribe solo ese día; los artículos en sí no se tocan."},
	{"About", "About", "Acerca de"},
	{"Action failed ({code}): {msg}", "Action failed ({code}): {msg}", "La acción falló ({code}): {msg}"},
	{"Active", "Active", "Activo"},
	{"Active on this author", "Active on this author", ""},
	{"Add", "Add", "Agregar"},
	{"Add sources in the Sources tab first.", "Add sources in the Sources tab first.", "Primero agregue fuentes en la pestaña Fuentes."},
	{"Admin Panel", "Admin Panel", "Panel de administración"},
	{"All", "All", "Todo"},
	{"All authors", "All authors", "Todos los autores"},
	{"All days", "All days", "Todos los días"},
	{"All sections", "All sections", "Todas las secciones"},
	{"Alphabetical", "Alphabetical", "Alfabético"},
	{"An author only researches the sources linked here. Cross-source corroboration across them is what drives relevance: a claim that several linked outlets carry independently rises, an unsourced one does not. Link a few trusted, independent outlets per author.", "An author only researches the sources linked here. Cross-source corroboration across them is what drives relevance: a claim that several linked outlets carry independently rises, an unsourced one does not. Link a few trusted, independent outlets per author.", "Un autor solo investiga las fuentes vinculadas aquí. La corroboración entre fuentes es lo que impulsa la relevancia: una afirmación que varios medios vinculados sostienen de forma independiente sube, una sin fuente no. Vincule unos pocos medios confiables e independientes por autor."},
	{"Article", "Article", "Artículo"},
	{"Article deleted.", "Article deleted.", "Artículo eliminado."},
	{"Article editor", "Article editor", "Editor de artículo"},
	{"Article saved.", "Article saved.", "Artículo guardado."},
	{"Articles", "Articles", "Artículos"},
	{"Ascending", "Ascending", "Ascendente"},
	{"Assigned to", "Assigned to", "Asignado a"},
	{"Author", "Author", "Autor"},
	{"Author editor", "Author editor", "Editor de autor"},
	{"Authors", "Authors", "Autores"},
	{"Avatar path", "Avatar path", "Ruta del avatar"},
	{"Avatar preview", "Avatar preview", "Vista previa del avatar"},
	{"Back", "Back", "Volver"},
	{"Beat", "Beat", "Sección"},
	{"Body", "Body", "Cuerpo"},
	{"Cancel", "Cancel", "Cancelar"},
	{"Card size", "Card size", "Tamaño"},
	{"Card span", "Card span", "Extensión"},
	{"Clear filters", "Clear filters", "Limpiar filtros"},
	{"Close", "Close", "Cerrar"},
	{"Co-owned mastheads collapse to one independent source for the corroboration gate. Give shared owners the same group so two papers under one owner count once, not twice, when a claim needs a second source.", "Co-owned mastheads collapse to one independent source for the corroboration gate. Give shared owners the same group so two papers under one owner count once, not twice, when a claim needs a second source.", "Las cabeceras de un mismo dueño se cuentan como una sola fuente independiente para el control de corroboración. Asigne el mismo grupo a los dueños compartidos para que dos periódicos de un mismo dueño cuenten una vez, no dos, cuando una afirmación necesita una segunda fuente."},
	{"Complete all author fields before saving.", "Complete all author fields before saving.", "Complete todos los campos del autor antes de guardar."},
	{"Confirm", "Confirm", "Confirmar"},
	{"Console sections", "Console sections", "Secciones de la consola"},
	{"Control panel", "Control panel", "Panel de control"},
	{"Could not create author: {msg}", "Could not create author: {msg}", "No se pudo crear el autor: {msg}"},
	{"Could not delete article ({code}): {msg}", "Could not delete article ({code}): {msg}", "No se pudo eliminar el artículo ({code}): {msg}"},
	{"Could not load article: {msg}", "Could not load article: {msg}", "No se pudo cargar el artículo: {msg}"},
	{"Could not load articles: {msg}", "Could not load articles: {msg}", "No se pudo cargar los artículos: {msg}"},
	{"Could not load authors: {msg}", "Could not load authors: {msg}", "No se pudo cargar los autores: {msg}"},
	{"Could not load portadas: {msg}", "Could not load portadas: {msg}", "No se pudo cargar las portadas: {msg}"},
	{"Could not load recomendado: {msg}", "Could not load recomendado: {msg}", "No se pudo cargar recomendado: {msg}"},
	{"Could not load sources: {msg}", "Could not load sources: {msg}", "No se pudo cargar las fuentes: {msg}"},
	{"Could not load topics: {msg}", "Could not load topics: {msg}", "No se pudo cargar los temas: {msg}"},
	{"Could not save ({code}): {msg}", "Could not save ({code}): {msg}", "No se pudo guardar ({code}): {msg}"},
	{"Could not save article ({code}): {msg}", "Could not save article ({code}): {msg}", "No se pudo guardar el artículo ({code}): {msg}"},
	{"Could not save portada ({code}): {msg}", "Could not save portada ({code}): {msg}", "No se pudo guardar la portada ({code}): {msg}"},
	{"Could not save recomendado ({code}): {msg}", "Could not save recomendado ({code}): {msg}", "No se pudo guardar recomendado ({code}): {msg}"},
	{"Create author", "Create author", "Crear autor"},
	{"Created {id}.", "Created {id}.", "Se creó {id}."},
	{"Creating...", "Creating...", "Creando..."},
	{"Dark", "Dark", "Oscuro"},
	{"Date", "Date", "Fecha"},
	{"Date order", "Date order", "Orden de fecha"},
	{"Day", "Day", "Día"},
	{"Days", "Days", "Días"},
	{"Delete", "Delete", "Eliminar"},
	{"Delete article", "Delete article", "Eliminar artículo"},
	{"Delete article?", "Delete article?", "¿Eliminar artículo?"},
	{"Deleting article...", "Deleting article...", "Eliminando artículo..."},
	{"Descending", "Descending", "Descendente"},
	{"Description", "Description", "Descripción"},
	{"Display name", "Display name", "Nombre visible"},
	{"Display name must contain letters or digits.", "Display name must contain letters or digits.", ""},
	{"Domain", "Domain", "Dominio"},
	{"Double card", "Double card", "Tarjeta doble"},
	{"Drag to reorder", "Drag to reorder", "Arrastrar para reordenar"},
	{"Edit article", "Edit article", "Editar artículo"},
	{"Enabled", "Enabled", "Habilitada"},
	{"Feed URLs (comma separated)", "Feed URLs (comma separated)", "URLs de feeds (separadas por comas)"},
	{"Feed type", "Feed type", "Tipo de feed"},
	{"Female", "Female", ""},
	{"Filter by active on this author", "Filter by active on this author", ""},
	{"Filter by author", "Filter by author", "Filtrar por autor"},
	{"Filter by day", "Filter by day", "Filtrar por día"},
	{"Filter by orientation", "Filter by orientation", "Filtrar por orientación"},
	{"Filter topics", "Filter topics", "Filtrar temas"},
	{"Full row", "Full row", "Fila completa"},
	{"Gender", "Gender", ""},
	{"Homepage", "Homepage", "Página principal"},
	{"Image", "Image", "Imagen"},
	{"Inactive", "Inactive", ""},
	{"Language", "Language", "Idioma"},
	{"Latest first", "Latest first", "Más recientes"},
	{"Left", "Left", "Izquierda"},
	{"Light", "Light", "Claro"},
	{"Linked sources", "Linked sources", "Fuentes vinculadas"},
	{"Loading article...", "Loading article...", "Cargando artículo..."},
	{"Loading articles...", "Loading articles...", "Cargando artículos..."},
	{"Loading authors...", "Loading authors...", "Cargando autores..."},
	{"Loading recomendado...", "Loading recomendado...", "Cargando recomendado..."},
	{"Loading sources...", "Loading sources...", "Cargando fuentes..."},
	{"Loading topics...", "Loading topics...", "Cargando temas..."},
	{"Main article", "Main article", "Artículo principal"},
	{"Make {title} a full row", "Make {title} a full row", "Convertir {title} en fila completa"},
	{"Male", "Male", ""},
	{"Media", "Media", "Media"},
	{"Most used", "Most used", "Más usados"},
	{"Move down", "Move down", "Bajar"},
	{"Move up", "Move up", "Subir"},
	{"Neutral", "Neutral", "Neutral"},
	{"Next day", "Next day", "Día siguiente"},
	{"No articles match.", "No articles match.", "Ningún artículo coincide."},
	{"No articles yet.", "No articles yet.", "Todavía no hay artículos."},
	{"No authors assigned", "No authors assigned", "Sin autores asignados"},
	{"No authors match.", "No authors match.", "Ningún autor coincide."},
	{"No authors yet.", "No authors yet.", "Todavía no hay autores."},
	{"No authors yet. Create one to get started.", "No authors yet. Create one to get started.", ""},
	{"No days", "No days", "Sin días"},
	{"No days match.", "No days match.", "Ningún día coincide."},
	{"No recommended articles selected.", "No recommended articles selected.", "No hay artículos recomendados seleccionados."},
	{"No sources match.", "No sources match.", "Ninguna fuente coincide."},
	{"No sources yet.", "No sources yet.", "Todavía no hay fuentes."},
	{"No topics yet.", "No topics yet.", "Todavía no hay temas."},
	{"Nonbinary", "Nonbinary", ""},
	{"Order by", "Order by", "Ordenar por"},
	{"Orientation", "Orientation", "Orientación"},
	{"Ownership group", "Ownership group", "Grupo de propiedad"},
	{"Place after {title}", "Place after {title}", "Colocar después de {title}"},
	{"Place before {title}", "Place before {title}", "Colocar antes de {title}"},
	{"Portada", "Portada", "Portada"},
	{"Portada saved.", "Portada saved.", ""},
	{"Primary", "Primary", "Principal"},
	{"Prompt instructions", "Prompt instructions", "Instrucciones de prompt"},
	{"Recomendado", "Recomendado", "Recomendado"},
	{"Recomendado saved.", "Recomendado saved.", "Recomendado guardado."},
	{"Removed / unresolved", "Removed / unresolved", "Eliminado / sin resolver"},
	{"Restore", "Restore", "Restaurar"},
	{"Right", "Right", "Derecha"},
	{"Role for {title}", "Role for {title}", "Rol de {title}"},
	{"Save", "Save", "Guardar"},
	{"Save article", "Save article", "Guardar artículo"},
	{"Save portada", "Save portada", ""},
	{"Saved.", "Saved.", "Guardado."},
	{"Saving...", "Saving...", "Guardando..."},
	{"Search", "Search", "Buscar"},
	{"Search articles", "Search articles", "Buscar artículos"},
	{"Search authors", "Search authors", "Buscar autores"},
	{"Search days", "Search days", "Buscar días"},
	{"Search results", "Search results", "Resultados de búsqueda"},
	{"Search title and description", "Search title and description", "Buscar título y descripción"},
	{"Section", "Section", "Sección"},
	{"Sections", "Sections", "Secciones"},
	{"Select a beat", "Select a beat", "Elija una sección"},
	{"Show", "Show", "Mostrar"},
	{"Single card", "Single card", "Tarjeta simple"},
	{"Source", "Source", "Fuente"},
	{"Source editor", "Source editor", "Editor de fuente"},
	{"Sources", "Sources", "Fuentes"},
	{"Style", "Style", "Estilo"},
	{"Subtitle", "Subtitle", "Subtítulo"},
	{"System", "System", "Sistema"},
	{"Text", "Text", "Texto"},
	{"Theme", "Theme", "Tema"},
	{"This article will be removed from this list. There is no recovery from this screen.", "This article will be removed from this list. There is no recovery from this screen.", "El artículo se quitará de esta lista. No hay recuperación desde esta pantalla."},
	{"Title", "Title", "Título"},
	{"Topics", "Topics", "Temas"},
	{"Topics are derived from the published article corpus, not a separate store. Filter or order them to inspect the tag surface.", "Topics are derived from the published article corpus, not a separate store. Filter or order them to inspect the tag surface.", "Los temas se derivan del corpus de artículos publicados, no de un registro separado. Filtre u ordene para revisar la superficie de etiquetas."},
	{"Unspecified", "Unspecified", ""},
	{"Up to {n} articles.", "Up to {n} articles.", "Hasta {n} artículos."},
	{"Who I am", "Who I am", "Quién soy"},
	{"YouTube", "YouTube", "YouTube"},
	{"offline", "offline", "fuera de línea"},
	{"online", "online", "en línea"},
	{"unknown", "unknown", "desconocido"},
}
