package adminweb

// Code-shaped data, generated once from the panel's actual t() call arguments (the live
// key set) by scratchpad/extract-livekeys.mjs, then committed. It is the source of record
// the seed command writes into panel_text: En is the English base every key is authored
// in (identical to the key, which is the English source string), Es preserves the panel's
// prior Spanish translation where one existed. The panel renders a single language
// (English) by injecting the en rows; the es rows are retained so no translation work is
// lost and a future translate pass has a base. Keys from removed panels (Runs/Editorial/
// Prompts/Health), option VALUES (active/inactive/off), and the server-rendered login
// strings are not t() arguments and are absent here.

// PanelTextSeedEntry is one seed row: the stable key, its English base value, and the
// preserved Spanish value ("" when the key never had a Spanish overlay).
type PanelTextSeedEntry struct {
	Key string
	En  string
	Es  string
}

// PanelTextSeed returns the live panel UI-string catalog: 314 keys.
func PanelTextSeed() []PanelTextSeedEntry {
	return panelTextSeed
}

var panelTextSeed = []PanelTextSeedEntry{
	{"(unset)", "(unset)", "(sin definir)"},
	{"A monthly schedule needs at least one day of the month.", "A monthly schedule needs at least one day of the month.", "Un cronograma mensual necesita al menos un día del mes."},
	{"A portada is one day's front-page plan. Pick a day, then order its articles (the first row is the day's lead), and mark any as important. Saving writes just that day; the articles themselves are untouched.", "A portada is one day's front-page plan. Pick a day, then order its articles (the first row is the day's lead), and mark any as important. Saving writes just that day; the articles themselves are untouched.", "Una portada es el plan de tapa de un día. Elija un día, luego ordene sus artículos (la primera fila es la nota de tapa del día) y marque los que sean importantes. Guardar escribe solo ese día; los artículos en sí no se tocan."},
	{"A schedule fires the newsroom's edition batch on its days at each listed time (the server's local wall clock). Preview holds every article for approval; auto publishes as soon as the gate passes. The executor runs while Docker runs: firings that come due while a batch is in flight queue behind it, and times missed while the executor is off are skipped, never replayed.", "A schedule fires the newsroom's edition batch on its days at each listed time (the server's local wall clock). Preview holds every article for approval; auto publishes as soon as the gate passes. The executor runs while Docker runs: firings that come due while a batch is in flight queue behind it, and times missed while the executor is off are skipped, never replayed.", "Un cronograma dispara el lote de edición en sus días, a cada hora listada (reloj local del servidor). Preview retiene para aprobación; auto publica al pasar la mesa. El ejecutor corre mientras Docker corre: los disparos que vencen con un lote en marcha se encolan detrás; las horas perdidas con el ejecutor apagado se saltean, nunca se repiten."},
	{"A schedule needs a name.", "A schedule needs a name.", "Un cronograma necesita un nombre."},
	{"A weekly schedule needs at least one weekday.", "A weekly schedule needs at least one weekday.", "Un cronograma semanal necesita al menos un día de la semana."},
	{"API key", "API key", "Clave de API"},
	{"About", "About", "Acerca de"},
	{"Acta (research read)", "Acta (research read)", "Acta (lectura de investigación)"},
	{"Action failed ({code}): {msg}", "Action failed ({code}): {msg}", "La acción falló ({code}): {msg}"},
	{"Active", "Active", "Activo"},
	{"Active fires on schedule; switched off it stays listed but never fires (paused).", "Active fires on schedule; switched off it stays listed but never fires (paused).", "Activo dispara según el cronograma; apagado queda en la lista pero nunca dispara (pausado)."},
	{"Active on this author", "Active on this author", ""},
	{"Add", "Add", "Agregar"},
	{"Add at least one time.", "Add at least one time.", "Agregue al menos una hora."},
	{"Add sources in the Sources tab first.", "Add sources in the Sources tab first.", "Primero agregue fuentes en la pestaña Fuentes."},
	{"Add time", "Add time", "Agregar hora"},
	{"Admin Panel", "Admin Panel", "Panel de administración"},
	{"All", "All", "Todo"},
	{"All authors", "All authors", "Todos los autores"},
	{"All days", "All days", "Todos los días"},
	{"All sections", "All sections", "Todas las secciones"},
	{"Alphabetical", "Alphabetical", "Alfabético"},
	{"An author only researches the sources linked here. Cross-source corroboration across them is what drives relevance: a claim that several linked outlets carry independently rises, an unsourced one does not. Link a few trusted, independent outlets per author.", "An author only researches the sources linked here. Cross-source corroboration across them is what drives relevance: a claim that several linked outlets carry independently rises, an unsourced one does not. Link a few trusted, independent outlets per author.", "Un autor solo investiga las fuentes vinculadas aquí. La corroboración entre fuentes es lo que impulsa la relevancia: una afirmación que varios medios vinculados sostienen de forma independiente sube, una sin fuente no. Vincule unos pocos medios confiables e independientes por autor."},
	{"Any OpenAI-compatible inference API with a Bearer key works here.", "Any OpenAI-compatible inference API with a Bearer key works here.", "Acá sirve cualquier API de inferencia compatible con OpenAI con clave Bearer."},
	{"Apr", "Apr", "Abr"},
	{"April", "April", "Abril"},
	{"Article", "Article", "Artículo"},
	{"Article deleted.", "Article deleted.", "Artículo eliminado."},
	{"Article editor", "Article editor", "Editor de artículo"},
	{"Article saved.", "Article saved.", "Artículo guardado."},
	{"Articles", "Articles", "Artículos"},
	{"Ascending", "Ascending", "Ascendente"},
	{"Assigned to", "Assigned to", "Asignado a"},
	{"Aug", "Aug", "Ago"},
	{"August", "August", "Agosto"},
	{"Author", "Author", "Autor"},
	{"Author editor", "Author editor", "Editor de autor"},
	{"Authors", "Authors", "Autores"},
	{"Auto", "Auto", "Auto"},
	{"Auto (publish on gate pass)", "Auto (publish on gate pass)", "Auto (publica al pasar la mesa)"},
	{"Automation", "Automation", "Automatización"},
	{"Automation sections", "Automation sections", "Secciones de automatización"},
	{"Avatar path", "Avatar path", "Ruta del avatar"},
	{"Avatar preview", "Avatar preview", "Vista previa del avatar"},
	{"Back", "Back", "Volver"},
	{"Beat", "Beat", "Sección"},
	{"Body", "Body", "Cuerpo"},
	{"Cadence", "Cadence", "Cadencia"},
	{"Cancel", "Cancel", "Cancelar"},
	{"Card size", "Card size", "Tamaño"},
	{"Card span", "Card span", "Extensión"},
	{"Clear filters", "Clear filters", "Limpiar filtros"},
	{"Close", "Close", "Cerrar"},
	{"Co-owned mastheads collapse to one independent source for the corroboration gate. Give shared owners the same group so two papers under one owner count once, not twice, when a claim needs a second source.", "Co-owned mastheads collapse to one independent source for the corroboration gate. Give shared owners the same group so two papers under one owner count once, not twice, when a claim needs a second source.", "Las cabeceras de un mismo dueño se cuentan como una sola fuente independiente para el control de corroboración. Asigne el mismo grupo a los dueños compartidos para que dos periódicos de un mismo dueño cuenten una vez, no dos, cuando una afirmación necesita una segunda fuente."},
	{"Complete all author fields before saving.", "Complete all author fields before saving.", "Complete todos los campos del autor antes de guardar."},
	{"Confirm", "Confirm", "Confirmar"},
	{"Console sections", "Console sections", "Secciones de la consola"},
	{"Control panel", "Control panel", "Panel de control"},
	{"Corrector", "Corrector", "Corrector"},
	{"Could not create author: {msg}", "Could not create author: {msg}", "No se pudo crear el autor: {msg}"},
	{"Could not delete article ({code}): {msg}", "Could not delete article ({code}): {msg}", "No se pudo eliminar el artículo ({code}): {msg}"},
	{"Could not load article: {msg}", "Could not load article: {msg}", "No se pudo cargar el artículo: {msg}"},
	{"Could not load articles: {msg}", "Could not load articles: {msg}", "No se pudo cargar los artículos: {msg}"},
	{"Could not load authors: {msg}", "Could not load authors: {msg}", "No se pudo cargar los autores: {msg}"},
	{"Could not load model settings: {msg}", "Could not load model settings: {msg}", "No se pudo cargar la configuración de modelos: {msg}"},
	{"Could not load portadas: {msg}", "Could not load portadas: {msg}", "No se pudo cargar las portadas: {msg}"},
	{"Could not load recomendado: {msg}", "Could not load recomendado: {msg}", "No se pudo cargar recomendado: {msg}"},
	{"Could not load schedules: {msg}", "Could not load schedules: {msg}", "No se pudieron cargar los cronogramas: {msg}"},
	{"Could not load sources: {msg}", "Could not load sources: {msg}", "No se pudo cargar las fuentes: {msg}"},
	{"Could not load topics: {msg}", "Could not load topics: {msg}", "No se pudo cargar los temas: {msg}"},
	{"Could not save ({code}): {msg}", "Could not save ({code}): {msg}", "No se pudo guardar ({code}): {msg}"},
	{"Could not save article ({code}): {msg}", "Could not save article ({code}): {msg}", "No se pudo guardar el artículo ({code}): {msg}"},
	{"Could not save portada ({code}): {msg}", "Could not save portada ({code}): {msg}", "No se pudo guardar la portada ({code}): {msg}"},
	{"Could not save recomendado ({code}): {msg}", "Could not save recomendado ({code}): {msg}", "No se pudo guardar recomendado ({code}): {msg}"},
	{"Create author", "Create author", "Crear autor"},
	{"Created {id}.", "Created {id}.", "Se creó {id}."},
	{"Creating...", "Creating...", "Creando..."},
	{"Custom run (has a prompt)", "Custom run (has a prompt)", "Corrida personalizada (con prompt)"},
	{"Daily", "Daily", "Diario"},
	{"Dark", "Dark", "Oscuro"},
	{"Date", "Date", "Fecha"},
	{"Date order", "Date order", "Orden de fecha"},
	{"Day", "Day", "Día"},
	{"Days", "Days", "Días"},
	{"Days of the month", "Days of the month", "Días del mes"},
	{"Dec", "Dec", "Dic"},
	{"December", "December", "Diciembre"},
	{"Delete", "Delete", "Eliminar"},
	{"Delete article", "Delete article", "Eliminar artículo"},
	{"Delete article?", "Delete article?", "¿Eliminar artículo?"},
	{"Deleting article...", "Deleting article...", "Eliminando artículo..."},
	{"Descending", "Descending", "Descendente"},
	{"Description", "Description", "Descripción"},
	{"Display name", "Display name", "Nombre visible"},
	{"Display name must contain letters or digits.", "Display name must contain letters or digits.", ""},
	{"Domain", "Domain", "Dominio"},
	{"Double card", "Double card", "Tarjeta doble"},
	{"Draft", "Draft", "Borrador"},
	{"Drag to reorder", "Drag to reorder", "Arrastrar para reordenar"},
	{"Each pipeline stage runs on the lane you pick: the local model or the remote API.", "Each pipeline stage runs on the lane you pick: the local model or the remote API.", "Cada etapa del pipeline corre en el carril que elijas: el modelo local o la API remota."},
	{"Edit article", "Edit article", "Editar artículo"},
	{"Edit schedule", "Edit schedule", "Editar cronograma"},
	{"Empty = generic run (whole newsroom). Write an instruction to make it a custom run.", "Empty = generic run (whole newsroom). Write an instruction to make it a custom run.", "Vacío = corrida genérica (toda la redacción). Escribí una instrucción para hacerla personalizada."},
	{"Empty prompt = a GENERIC run: the whole newsroom pitches and the jefe picks freely. With a prompt it is a CUSTOM run: your instruction (e.g. \"using this author cover the march downtown\") steers what the authors pitch and what the jefe selects.", "Empty prompt = a GENERIC run: the whole newsroom pitches and the jefe picks freely. With a prompt it is a CUSTOM run: your instruction (e.g. \"using this author cover the march downtown\") steers what the authors pitch and what the jefe selects.", "Prompt vacío = corrida GENÉRICA: toda la redacción propone y el jefe elige libre. Con prompt es una corrida PERSONALIZADA: tu instrucción (p. ej. \"con este autor cubrí la marcha del centro\") guía qué proponen los autores y qué elige el jefe."},
	{"Enabled", "Enabled", "Habilitada"},
	{"Endpoint", "Endpoint", "Endpoint"},
	{"Every day", "Every day", "Todos los días"},
	{"Executor", "Executor", "Ejecutor"},
	{"Executor offline", "Executor offline", "Ejecutor apagado"},
	{"Executor offline: showing the last saved values.", "Executor offline: showing the last saved values.", "Ejecutor apagado: se muestra lo último guardado."},
	{"Executor status", "Executor status", "Estado del ejecutor"},
	{"Feb", "Feb", "Feb"},
	{"February", "February", "Febrero"},
	{"Feed URLs (comma separated)", "Feed URLs (comma separated)", "URLs de feeds (separadas por comas)"},
	{"Feed type", "Feed type", "Tipo de feed"},
	{"Female", "Female", ""},
	{"Filter by active on this author", "Filter by active on this author", ""},
	{"Filter by author", "Filter by author", "Filtrar por autor"},
	{"Filter by day", "Filter by day", "Filtrar por día"},
	{"Filter by orientation", "Filter by orientation", "Filtrar por orientación"},
	{"Filter topics", "Filter topics", "Filtrar temas"},
	{"Fires every day at the listed times.", "Fires every day at the listed times.", "Dispara todos los días a las horas listadas."},
	{"Fri", "Fri", "Vie"},
	{"Full row", "Full row", "Fila completa"},
	{"Gate (editor de mesa)", "Gate (editor de mesa)", "Mesa (editor de mesa)"},
	{"Gender", "Gender", ""},
	{"Generic run (whole newsroom)", "Generic run (whole newsroom)", "Corrida genérica (toda la redacción)"},
	{"Homepage", "Homepage", "Página principal"},
	{"Idle", "Idle", "En espera"},
	{"Image", "Image", "Imagen"},
	{"Inactive", "Inactive", ""},
	{"Jan", "Jan", "Ene"},
	{"January", "January", "Enero"},
	{"Jul", "Jul", "Jul"},
	{"July", "July", "Julio"},
	{"Jun", "Jun", "Jun"},
	{"June", "June", "Junio"},
	{"Key saved. Leave empty to keep it.", "Key saved. Leave empty to keep it.", "Clave guardada. Dejá vacío para conservarla."},
	{"Lane", "Lane", "Carril"},
	{"Language", "Language", "Idioma"},
	{"Last run", "Last run", "Última corrida"},
	{"Latest first", "Latest first", "Más recientes"},
	{"Left", "Left", "Izquierda"},
	{"Light", "Light", "Claro"},
	{"Linked sources", "Linked sources", "Fuentes vinculadas"},
	{"Loading article...", "Loading article...", "Cargando artículo..."},
	{"Loading articles...", "Loading articles...", "Cargando artículos..."},
	{"Loading authors...", "Loading authors...", "Cargando autores..."},
	{"Loading recomendado...", "Loading recomendado...", "Cargando recomendado..."},
	{"Loading schedules...", "Loading schedules...", "Cargando cronogramas..."},
	{"Loading sources...", "Loading sources...", "Cargando fuentes..."},
	{"Loading topics...", "Loading topics...", "Cargando temas..."},
	{"Local (llama.cpp)", "Local (llama.cpp)", "Local (llama.cpp)"},
	{"Main article", "Main article", "Artículo principal"},
	{"Make {title} a full row", "Make {title} a full row", "Convertir {title} en fila completa"},
	{"Male", "Male", ""},
	{"Mar", "Mar", "Mar"},
	{"March", "March", "Marzo"},
	{"May", "May", "Mayo"},
	{"Media", "Media", "Media"},
	{"Mode", "Mode", "Modo"},
	{"Model", "Model", "Modelo"},
	{"Model (llama.cpp)", "Model (llama.cpp)", "Modelo (llama.cpp)"},
	{"Models", "Models", "Modelos"},
	{"Mon", "Mon", "Lun"},
	{"Month", "Month", "Mes"},
	{"Monthly", "Monthly", "Mensual"},
	{"Most used", "Most used", "Más usados"},
	{"Move down", "Move down", "Bajar"},
	{"Move up", "Move up", "Subir"},
	{"Name", "Name", "Nombre"},
	{"Neutral", "Neutral", "Neutral"},
	{"New schedule", "New schedule", "Nuevo cronograma"},
	{"Next day", "Next day", "Día siguiente"},
	{"Next month", "Next month", "Mes siguiente"},
	{"Next run", "Next run", "Próxima corrida"},
	{"No articles match.", "No articles match.", "Ningún artículo coincide."},
	{"No articles yet.", "No articles yet.", "Todavía no hay artículos."},
	{"No authors assigned", "No authors assigned", "Sin autores asignados"},
	{"No authors match.", "No authors match.", "Ningún autor coincide."},
	{"No authors yet.", "No authors yet.", "Todavía no hay autores."},
	{"No authors yet. Create one to get started.", "No authors yet. Create one to get started.", ""},
	{"No batch in flight.", "No batch in flight.", "Ningún lote en marcha."},
	{"No days", "No days", "Sin días"},
	{"No days match.", "No days match.", "Ningún día coincide."},
	{"No key yet: paste it here or set OPENROUTER_API_KEY in .env.", "No key yet: paste it here or set OPENROUTER_API_KEY in .env.", "Sin clave: pegala acá o definí OPENROUTER_API_KEY en .env."},
	{"No recommended articles selected.", "No recommended articles selected.", "No hay artículos recomendados seleccionados."},
	{"No runs recorded yet.", "No runs recorded yet.", "Todavía no hay corridas registradas."},
	{"No schedules yet. Create one to put the newsroom on a clock.", "No schedules yet. Create one to put the newsroom on a clock.", "Todavía no hay cronogramas. Cree uno para poner la redacción en horario."},
	{"No sources match.", "No sources match.", "Ninguna fuente coincide."},
	{"No sources yet.", "No sources yet.", "Todavía no hay fuentes."},
	{"No times yet.", "No times yet.", "Todavía no hay horas."},
	{"No topics yet.", "No topics yet.", "Todavía no hay temas."},
	{"Nonbinary", "Nonbinary", ""},
	{"Nov", "Nov", "Nov"},
	{"November", "November", "Noviembre"},
	{"Oct", "Oct", "Oct"},
	{"October", "October", "Octubre"},
	{"On days of the month", "On days of the month", "En los días del mes"},
	{"On weekdays", "On weekdays", "En los días de la semana"},
	{"OpenRouter", "OpenRouter", "OpenRouter"},
	{"Order by", "Order by", "Ordenar por"},
	{"Orientation", "Orientation", "Orientación"},
	{"Outline", "Outline", "Esquema"},
	{"Ownership group", "Ownership group", "Grupo de propiedad"},
	{"Paused", "Paused", "Pausado"},
	{"Pick a time", "Pick a time", "Elegir una hora"},
	{"Pick the days of the month.", "Pick the days of the month.", "Elegí los días del mes."},
	{"Pick weekdays on the header row.", "Pick weekdays on the header row.", "Elegí los días de la semana en la fila de arriba."},
	{"Place after {title}", "Place after {title}", "Colocar después de {title}"},
	{"Place before {title}", "Place before {title}", "Colocar antes de {title}"},
	{"Portada", "Portada", "Portada"},
	{"Portada saved.", "Portada saved.", ""},
	{"Preview", "Preview", "Preview"},
	{"Preview (hold for approval)", "Preview (hold for approval)", "Preview (retiene para aprobación)"},
	{"Previous month", "Previous month", "Mes anterior"},
	{"Primary", "Primary", "Principal"},
	{"Prod", "Prod", "Prod"},
	{"Prompt (optional)", "Prompt (optional)", "Prompt (opcional)"},
	{"Prompt instructions", "Prompt instructions", "Instrucciones de prompt"},
	{"Provider", "Provider", "Proveedor"},
	{"Provider...", "Provider...", "Proveedor..."},
	{"Queued", "Queued", "En cola"},
	{"Queued:", "Queued:", "En cola:"},
	{"RUNNING", "RUNNING", "CORRIENDO"},
	{"Recent runs", "Recent runs", "Corridas recientes"},
	{"Recomendado", "Recomendado", "Recomendado"},
	{"Recomendado saved.", "Recomendado saved.", "Recomendado guardado."},
	{"Remote API", "Remote API", "API remota"},
	{"Remove {time}", "Remove {time}", "Quitar {time}"},
	{"Removed / unresolved", "Removed / unresolved", "Eliminado / sin resolver"},
	{"Research queries", "Research queries", "Consultas de investigación"},
	{"Restore", "Restore", "Restaurar"},
	{"Right", "Right", "Derecha"},
	{"Role for {title}", "Role for {title}", "Rol de {title}"},
	{"Run history", "Run history", "Historial de corridas"},
	{"Sat", "Sat", "Sáb"},
	{"Save", "Save", "Guardar"},
	{"Save article", "Save article", "Guardar artículo"},
	{"Save models", "Save models", "Guardar modelos"},
	{"Save portada", "Save portada", ""},
	{"Save stages", "Save stages", "Guardar etapas"},
	{"Saved.", "Saved.", "Guardado."},
	{"Saved. The next firing uses this.", "Saved. The next firing uses this.", "Guardado. La próxima corrida usa esto."},
	{"Saving...", "Saving...", "Guardando..."},
	{"Schedule", "Schedule", "Cronograma"},
	{"Schedule editor", "Schedule editor", "Editor de cronograma"},
	{"Schedules", "Schedules", "Cronogramas"},
	{"Search", "Search", "Buscar"},
	{"Search articles", "Search articles", "Buscar artículos"},
	{"Search authors", "Search authors", "Buscar autores"},
	{"Search days", "Search days", "Buscar días"},
	{"Search results", "Search results", "Resultados de búsqueda"},
	{"Search title and description", "Search title and description", "Buscar título y descripción"},
	{"Section", "Section", "Sección"},
	{"Sections", "Sections", "Secciones"},
	{"Select a beat", "Select a beat", "Elija una sección"},
	{"Sep", "Sep", "Sep"},
	{"September", "September", "Septiembre"},
	{"Settings", "Settings", "Configuración"},
	{"Show", "Show", "Mostrar"},
	{"Show the key", "Show the key", "Mostrar la clave"},
	{"Single card", "Single card", "Tarjeta simple"},
	{"Source", "Source", "Fuente"},
	{"Source editor", "Source editor", "Editor de fuente"},
	{"Sources", "Sources", "Fuentes"},
	{"Stage", "Stage", "Etapa"},
	{"Stages", "Stages", "Etapas"},
	{"Status", "Status", "Estado"},
	{"Style", "Style", "Estilo"},
	{"Subtitle", "Subtitle", "Subtítulo"},
	{"Sun", "Sun", "Dom"},
	{"System", "System", "Sistema"},
	{"Tap the weekday initials to pick the days", "Tap the weekday initials to pick the days", "Tocá las iniciales de los días para elegirlos"},
	{"Text", "Text", "Texto"},
	{"The time {time} is already on the list.", "The time {time} is already on the list.", "La hora {time} ya está en la lista."},
	{"Theme", "Theme", "Tema"},
	{"These are the endpoints and models the scheduled batches actually run on, live from the executor. Edit and save: the next firing uses what you see here.", "These are the endpoints and models the scheduled batches actually run on, live from the executor. Edit and save: the next firing uses what you see here.", "Estos son los endpoints y modelos con los que corren los lotes programados, en vivo desde el ejecutor. Editá y guardá: la próxima corrida usa lo que ves acá."},
	{"This article will be removed from this list. There is no recovery from this screen.", "This article will be removed from this list. There is no recovery from this screen.", "El artículo se quitará de esta lista. No hay recuperación desde esta pantalla."},
	{"Thu", "Thu", "Jue"},
	{"Time", "Time", "Hora"},
	{"Times", "Times", "Horas"},
	{"Times (several per day allowed)", "Times (several per day allowed)", "Horas (se permiten varias por día)"},
	{"Title", "Title", "Título"},
	{"Topics", "Topics", "Temas"},
	{"Topics are derived from the published article corpus, not a separate store. Filter or order them to inspect the tag surface.", "Topics are derived from the published article corpus, not a separate store. Filter or order them to inspect the tag surface.", "Los temas se derivan del corpus de artículos publicados, no de un registro separado. Filtre u ordene para revisar la superficie de etiquetas."},
	{"Tue", "Tue", "Mar"},
	{"Unspecified", "Unspecified", ""},
	{"Up to {n} articles.", "Up to {n} articles.", "Hasta {n} artículos."},
	{"Verify", "Verify", "Verificar"},
	{"Wed", "Wed", "Mié"},
	{"Weekdays", "Weekdays", "Días de la semana"},
	{"Weekly", "Weekly", "Semanal"},
	{"Who I am", "Who I am", "Quién soy"},
	{"YouTube", "YouTube", "YouTube"},
	{"auto", "auto", "auto"},
	{"checked {s}s ago", "checked {s}s ago", "verificado hace {s} s"},
	{"down", "down", "caído"},
	{"failed", "failed", "falló"},
	{"healthy", "healthy", "sano"},
	{"key rejected", "key rejected", "clave rechazada"},
	{"never", "never", "nunca"},
	{"never ran", "never ran", "nunca corrió"},
	{"no key", "no key", "sin clave"},
	{"no report from the executor", "no report from the executor", "sin reporte del ejecutor"},
	{"offline", "offline", "fuera de línea"},
	{"ok", "ok", "ok"},
	{"online", "online", "en línea"},
	{"open", "open", "abrir"},
	{"preview", "preview", "preview"},
	{"queued", "queued", "en cola"},
	{"running", "running", "corriendo"},
	{"unknown", "unknown", "desconocido"},
}
